# Generated by Django 4.1.6 on 2023-02-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MageneApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='STAT_AGEMAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AGEMOYEN', models.DecimalField(decimal_places=19, max_digits=19, null=True)),
                ('SIECLE', models.IntegerField(null=True)),
                ('GENRE', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='STAT_ESPVIE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ESPVIEMOYEN', models.DecimalField(decimal_places=19, max_digits=19, null=True)),
                ('SIECLE', models.IntegerField(null=True)),
                ('GENRE', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='STAT_LIEUX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COMMUNE', models.CharField(max_length=20, null=True)),
                ('OCCURENCE', models.IntegerField(null=True)),
                ('LATTITUDE', models.DecimalField(decimal_places=19, max_digits=19, null=True)),
                ('LONGITUDE', models.DecimalField(decimal_places=19, max_digits=19, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='STAT_PATRO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOM', models.CharField(max_length=20, null=True)),
                ('OCCURENCE', models.IntegerField(null=True)),
            ],
        ),
    ]
