# Generated by Django 4.1.6 on 2023-02-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MageneApp', '0002_stat_agemar_stat_espvie_stat_lieux_stat_patro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat_agemar',
            name='AGEMOYEN',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stat_espvie',
            name='ESPVIEMOYEN',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stat_lieux',
            name='LATTITUDE',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stat_lieux',
            name='LONGITUDE',
            field=models.FloatField(null=True),
        ),
    ]
