# Generated by Django 4.1.6 on 2023-04-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MageneApp', '0003_alter_stat_agemar_agemoyen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACTES',
            fields=[
                ('NUMACTES', models.IntegerField(primary_key=True, serialize=False)),
                ('LOGIN', models.CharField(max_length=20, null=True)),
                ('TYPE', models.CharField(max_length=20, null=True)),
                ('INTITULE', models.CharField(max_length=100, null=True)),
                ('DATE', models.CharField(max_length=20, null=True)),
                ('IMG_ACTES', models.ImageField(upload_to='img/actes')),
                ('NOM1', models.CharField(max_length=20, null=True)),
                ('NOM2', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
