# Generated by Django 4.1.6 on 2023-04-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MageneApp', '0004_actes'),
    ]

    operations = [
        migrations.AddField(
            model_name='actes',
            name='PRENOM1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='actes',
            name='PRENOM2',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
