# Generated by Django 4.1.6 on 2023-05-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MageneApp', '0005_actes_prenom1_actes_prenom2'),
    ]

    operations = [
        migrations.AddField(
            model_name='actes',
            name='DATE_ACTE',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='actes',
            name='LINKACTE',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='actes',
            name='NUMPART_ACTE',
            field=models.CharField(choices=[('1', 'PART 1'), ('2', 'PART 2'), ('3', 'PART 3'), ('4', 'PART 4')], default='1', max_length=1),
        ),
    ]
