# Generated by Django 4.1.6 on 2023-05-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MageneApp', '0006_actes_date_acte_actes_linkacte_actes_numpart_acte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actes',
            name='IMG_ACTES',
            field=models.ImageField(blank=True, null=True, upload_to='img/actes'),
        ),
        migrations.AlterField(
            model_name='actes',
            name='LINKACTE',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
