# Generated by Django 4.1.6 on 2023-05-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MageneApp', '0007_alter_actes_img_actes_alter_actes_linkacte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actes',
            name='TYPE',
            field=models.CharField(choices=[('', 'Vide'), ('MARIAGE', 'MARIAGE'), ('NAISSANCE', 'NAISSANCE'), ('DECES', 'DECES')], default='', max_length=20),
        ),
    ]
