# Generated by Django 4.1.6 on 2023-05-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MageneApp', '0008_alter_actes_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actes',
            name='DATE',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='actes',
            name='INTITULE',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='actes',
            name='LOGIN',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='actes',
            name='NOM2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='actes',
            name='PRENOM2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
