# Generated by Django 4.1.6 on 2023-07-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MageneApp', '0010_genusers_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='genusers_profil',
            name='DATEMODIFIED',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='genusers_profil',
            name='LASTCONNECTION',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='genusers_profil',
            name='NBCONNECTIONS',
            field=models.IntegerField(null=True),
        ),
    ]
